/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import javax.swing.JOptionPane;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalData;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class AddCityCommunity extends javax.swing.JFrame {

    /**
     * Creates new form AddCityCommunity
     */
    
    DoctorDirectory DocDirectory;
    HospitalDirectory HospDirectory;
    PatientDirectory PatDirectory;
    CityDirectory cityDirectory;
     CommunityDirectory CommDirectory;
     EncounterHistory EncHistory;
    
    public AddCityCommunity() {
        initComponents();
    }

    AddCityCommunity(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory,  CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         initComponents();

        this.DocDirectory = DocDirectory;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
         this.EncHistory = EncHistory;
         
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JBackAddCityCommBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JCityCb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JCommCb = new javax.swing.JComboBox<>();
        JCountryCb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JPincodeCb = new javax.swing.JComboBox<>();
        JBtnSaveComm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Community Details");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 80));

        JBackAddCityCommBtn.setBackground(new java.awt.Color(0, 153, 204));
        JBackAddCityCommBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        JBackAddCityCommBtn.setText("Back");
        JBackAddCityCommBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackAddCityCommBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackAddCityCommBtnMouseClicked(evt);
            }
        });
        JBackAddCityCommBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackAddCityCommBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JBackAddCityCommBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 150, 80));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("City");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 30));

        JCityCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCityCbActionPerformed(evt);
            }
        });
        jPanel1.add(JCityCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 210, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Community");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 80, 30));

        jPanel1.add(JCommCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 210, 30));

        jPanel1.add(JCountryCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 210, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Country");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 70, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pin Code");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 70, 30));

        jPanel1.add(JPincodeCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 210, 30));

        JBtnSaveComm.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JBtnSaveComm.setForeground(new java.awt.Color(0, 102, 153));
        JBtnSaveComm.setText("Save");
        JBtnSaveComm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnSaveCommMouseClicked(evt);
            }
        });
        jPanel1.add(JBtnSaveComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackAddCityCommBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackAddCityCommBtnMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_JBackAddCityCommBtnMouseClicked

    private void JBackAddCityCommBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackAddCityCommBtnActionPerformed
        // TODO add your handling code here:

        CommunityAdmins CAD2 = new CommunityAdmins(DocDirectory, HospDirectory, PatDirectory, cityDirectory,CommDirectory, EncHistory);
        CAD2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBackAddCityCommBtnActionPerformed

    private void JCityCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCityCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCityCbActionPerformed

    private void JBtnSaveCommMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnSaveCommMouseClicked
        // TODO add your handling code here:
        
        String city = JCityCb.getSelectedItem().toString();
        String communityName = JCommCb.getSelectedItem().toString();
        String pincode = JPincodeCb.getSelectedItem().toString();
        String country = JCountryCb.getSelectedItem().toString();
        
        if (communityName.isEmpty() || city.isEmpty() 
                || pincode.isEmpty() || country.isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Please enter all fields",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);          
                }
        else{
        HospitalData HD3 = HospDirectory.addNewHospData();
        
        Community hCommunity = new Community();
        hCommunity.setCommunityName(communityName);
        HD3.setCommunity(hCommunity);
        
        City hCity = new City();
        hCity.setCity(city);
        HD3.setCity(hCity);
        
        Community hPincode = new Community();
        hPincode.setPincode(pincode);
        HD3.setPincode(hPincode);
        
        City hCountry = new City();
        hCountry.setCountry(country);
        HD3.setCountry(hCountry);
        }
        
    }//GEN-LAST:event_JBtnSaveCommMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCityCommunity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCityCommunity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCityCommunity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCityCommunity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCityCommunity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBackAddCityCommBtn;
    private javax.swing.JButton JBtnSaveComm;
    private javax.swing.JComboBox<Object> JCityCb;
    private javax.swing.JComboBox<Object> JCommCb;
    private javax.swing.JComboBox<Object> JCountryCb;
    private javax.swing.JComboBox<Object> JPincodeCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
