/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.awt.event.KeyEvent;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.DoctorDirectory;
import model.HospitalData;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class AddHospitalDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddHospitalDetails
     */
    
      HospitalDirectory HospDirectory;
      DoctorDirectory DocDirectory;
      PatientDirectory PatDirectory;
 
    private AddHospitalDetails() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
    }
      
//    public AddHospitalDetails(HospitalDirectory HospDirectory) {
//        initComponents();
//        
//        this.HospDirectory = HospDirectory;
//    }

//    private AddHospitalDetails(HospitalDirectory HospDirectory, DoctorDirectory DocDirectory) {
//        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        initComponents();
//    }

    AddHospitalDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.DocDirectory = DocDirectory;
    }

    

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JBackAddDoctorButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JHospID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JPhoneNoHosp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JEmailHosp = new javax.swing.JTextField();
        JSaveHospButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JNameHosp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hospital Details");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 80));

        JBackAddDoctorButton.setBackground(new java.awt.Color(0, 153, 204));
        JBackAddDoctorButton.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        JBackAddDoctorButton.setText("Back");
        JBackAddDoctorButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackAddDoctorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackAddDoctorButtonMouseClicked(evt);
            }
        });
        JBackAddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackAddDoctorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JBackAddDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 150, 80));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hospital ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 80, 30));

        JHospID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHospIDActionPerformed(evt);
            }
        });
        JHospID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JHospIDKeyPressed(evt);
            }
        });
        jPanel2.add(JHospID, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 160, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 80, 30));

        JPhoneNoHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPhoneNoHospActionPerformed(evt);
            }
        });
        JPhoneNoHosp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPhoneNoHospKeyPressed(evt);
            }
        });
        jPanel2.add(JPhoneNoHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 160, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 80, 30));

        JEmailHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmailHospActionPerformed(evt);
            }
        });
        jPanel2.add(JEmailHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 160, 30));

        JSaveHospButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JSaveHospButton.setForeground(new java.awt.Color(0, 102, 153));
        JSaveHospButton.setText("Save");
        JSaveHospButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSaveHospButtonMouseClicked(evt);
            }
        });
        jPanel2.add(JSaveHospButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 630, 160, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hospital Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 110, 30));

        JNameHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNameHospActionPerformed(evt);
            }
        });
        JNameHosp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JNameHospKeyPressed(evt);
            }
        });
        jPanel2.add(JNameHosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 910));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackAddDoctorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackAddDoctorButtonMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_JBackAddDoctorButtonMouseClicked

    private void JBackAddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackAddDoctorButtonActionPerformed
        // TODO add your handling code here:

        HospitalDetailsAdmin HDA = new HospitalDetailsAdmin(DocDirectory, HospDirectory, PatDirectory);
        HDA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBackAddDoctorButtonActionPerformed

    private void JHospIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHospIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JHospIDActionPerformed

    private void JPhoneNoHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPhoneNoHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPhoneNoHospActionPerformed

    private void JEmailHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmailHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEmailHospActionPerformed

    private void JSaveHospButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSaveHospButtonMouseClicked
        // TODO add your handling code here:

        String hospID = JHospID.getText();
        String hospname = JNameHosp.getText();
        String phoneNohosp = JPhoneNoHosp.getText();
        String emailhosp = JEmailHosp.getText();
        int length = phoneNohosp.length();

        //DocData dd = DocDirectory.addNewDocData();
        if (hospID.isEmpty() || hospname.isEmpty()|| phoneNohosp.isEmpty()|| emailhosp.isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Please enter all fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else if(length<10){
            JOptionPane.showMessageDialog(this,
                "Please enter cell no of 10 digits",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailhosp)))
        {
            JOptionPane.showMessageDialog(null,
                "Please enter a valid email",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            HospitalData hd = HospDirectory.addNewHospData();
            hd.setHospitalName(hospname);
            hd.setHospitalID(hospID);
            hd.setPhoneNo(phoneNohosp);
            hd.setEmailAddress(emailhosp);
            JOptionPane.showMessageDialog(this, "New record added");

            JHospID.setText("");
            JNameHosp.setText("");
            JPhoneNoHosp.setText("");
            JEmailHosp.setText("");

        }
        //String DocID = JDocID.getText();
        //String FName

        /*
        DoctorDirectory DocDirectory = new DoctorDirectory();
        DocDirectory.setDocID(JDocID.getText());
        DocDirec.setFNameDoc(JFNameDoc.getText());
        DocDirec.setLNameDoc(JLNameDoc.getText());
        DocDirec.setAgeDoc(Integer.parseInt(JAgeDoc.getText()));
        DocDirec.setBGroupDoc(JBGroupDoc.getText());
        DocDirec.setGenderDoc(JGenderDoc.getSelectedItem().toString());
        DocDirec.setDepartmentDoc(JDepartmentDoc.getSelectedItem().toString());
        DocDirec.setAddressDoc(JAddressDoc.getText());
        DocDirec.setCityDoc(JCityDoc.getText());
        DocDirec.setPhoneNoDoc(Integer.parseInt(JPhoneNoDoc.getText()));
        DocDirec.setJoiningDateDoc(JJoiningDateDoc.getDate());

        */

        /*
        if (DocDirec.getDocID().isEmpty() || DocDirec.getFNameDoc().isEmpty()|| DocDirec.getLNameDoc().isEmpty() || /*DocDirec.getAgeDoc().isEmpty()|| DocDirec.getBGroupDoc().isEmpty()
            || DocDirec.getGenderDoc().isEmpty() || DocDirec.getDepartmentDoc().isEmpty() || DocDirec.getAddressDoc().isEmpty() ||
            DocDirec.getPhoneNoDoc().isEmpty() ||  DocDirec.getCityDoc().isEmpty() /*|| DocDirec.getJoiningDateDoc().isEmpty)){
        JOptionPane.showMessageDialog(this,
            "Please enter all fields",
            "Try Again",
            JOptionPane.ERROR_MESSAGE);
        } else if(DocDirec.getPhoneNoDoc()<10){
            JOptionPane.showMessageDialog(this,
                "Please enter cell no of 10 digits",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(this, "Doctor Details Added");

            JDocID.setText("");
            JFNameDoc.setText("");
            JLNameDoc.setText("");
            JAgeDoc.setText("");
            JBGroupDoc.setText("");
            JGenderDoc.setSelectedIndex(0);
            JDepartmentDoc.setSelectedIndex(0);
            JCityDoc.setText("");
            JAddressDoc.setText("");
            JPhoneNoDoc.setText("");

        }

        /*else {
            ViewDoctorDetails Vdd = new ViewDoctorDetails();
            DefaultTableModel model = (DefaultTableModel) Vdd.JTableDoc.getModel();
            model.addRow( new Object[] {name, empid, age, gender, date, level, teaminfo,
                positiontitle, cellphoneno, email, ImageLabel});

        TFName.setText("");
        TFEmpID.setText("");
        TFAge.setText("");
        TFGender.setSelectedIndex(0);
        //TFDateChooser.setDate("yyyy-MM-dd");
        //TFDateChooser.setCalendar(null);
        TFLevel.setSelectedIndex(0);
        TFTeamInfo.setText("");
        TFPositionTitle.setText("");
        TFCellPhoneNo.setText("");
        TFEmailAdd.setText("");
        image_txt.setText("");

        }
        */
    }//GEN-LAST:event_JSaveHospButtonMouseClicked

    private void JNameHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNameHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNameHospActionPerformed

    private void JHospIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JHospIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JHospIDKeyPressed

    private void JNameHospKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JNameHospKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            JNameHosp.setEditable(true);
        } else {
            JNameHosp.setEditable(false);
        }
    }//GEN-LAST:event_JNameHospKeyPressed

    private void JPhoneNoHospKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPhoneNoHospKeyPressed
        // TODO add your handling code here:
        try{
            String CellNumber = JPhoneNoHosp.getText();
            int length = CellNumber.length();
            char c = evt.getKeyChar();

            //check for number 0 to 9
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                //check for length not more than 10 digit
                if(length<10){
                    JPhoneNoHosp.setEditable(true);

                } else{
                    JPhoneNoHosp.setEditable(false);
                }
            }else{
                if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    JPhoneNoHosp.setEditable(true);
                } else{
                    JPhoneNoHosp.setEditable(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_JPhoneNoHospKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHospitalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHospitalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHospitalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHospitalDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
         HospitalDirectory HospDirectory;
         DoctorDirectory DocDirectory;
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHospitalDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBackAddDoctorButton;
    private javax.swing.JTextField JEmailHosp;
    private javax.swing.JTextField JHospID;
    private javax.swing.JTextField JNameHosp;
    private javax.swing.JTextField JPhoneNoHosp;
    private javax.swing.JButton JSaveHospButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
