/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.House;
import model.PatData;
import model.PatientDirectory;


/**
 *
 * @author anupamaditya
 */
public class AddPatientDetails extends javax.swing.JFrame {

    /**
     * Creates new form AddPatientDetails
     */
    
      PatientDirectory PatDirectory;
       DoctorDirectory DocDirectory;
       HospitalDirectory HospDirectory;
       CityDirectory cityDirectory;
       CommunityDirectory CommDirectory;
       EncounterHistory EncHistory;

    
    private AddPatientDetails() {
       //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       initComponents();
    }   
       
    public AddPatientDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory,  CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        initComponents();
        
        this.DocDirectory = DocDirectory;   //we are pushing whole reference to DoctorDirectory
        this.HospDirectory = HospDirectory;
        this.PatDirectory = PatDirectory; 
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
        this.EncHistory = EncHistory;
        
        
    }
    
    
    


//    AddPatientDetails(PatientDirectory PatDirectory, HospitalDirectory HospDirectory, DoctorDirectory DocDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPatID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JFNamePat = new javax.swing.JTextField();
        JLNamePat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JAgePat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JBGroupPat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JGenderPat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        JAddressPat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JPhoneNoPat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JCityPat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JVisitDatePat = new com.toedter.calendar.JDateChooser();
        JSaveDocButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        JBackAddDoctorButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        JPinCodePat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JEmailPat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JHeightPat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JWeightPat = new javax.swing.JTextField();
        JCommunityPat = new javax.swing.JTextField();
        JCountryPat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visit Date");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 90, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 30));
        jPanel2.add(JPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        JFNamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JFNamePatKeyPressed(evt);
            }
        });
        jPanel2.add(JFNamePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, 30));

        JLNamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JLNamePatKeyPressed(evt);
            }
        });
        jPanel2.add(JLNamePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 160, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, 30));

        JAgePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JAgePatKeyPressed(evt);
            }
        });
        jPanel2.add(JAgePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, 30));
        jPanel2.add(JBGroupPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 160, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blood Group");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 100, 30));

        JGenderPat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " ", " " }));
        JGenderPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JGenderPatActionPerformed(evt);
            }
        });
        jPanel2.add(JGenderPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 30));
        jPanel2.add(JAddressPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 260, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Street Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, 40));

        JPhoneNoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPhoneNoPatKeyPressed(evt);
            }
        });
        jPanel2.add(JPhoneNoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 150, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 80, 40));
        jPanel2.add(JCityPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 80, 40));
        jPanel2.add(JVisitDatePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 150, 30));

        JSaveDocButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JSaveDocButton.setForeground(new java.awt.Color(0, 102, 153));
        JSaveDocButton.setText("Save");
        JSaveDocButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSaveDocButtonMouseClicked(evt);
            }
        });
        jPanel2.add(JSaveDocButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 830, 150, 30));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Patient Details");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 80));

        JBackAddDoctorButton.setBackground(new java.awt.Color(0, 153, 204));
        JBackAddDoctorButton.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        JBackAddDoctorButton.setText("Back");
        JBackAddDoctorButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackAddDoctorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackAddDoctorButtonMouseClicked(evt);
            }
        });
        JBackAddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackAddDoctorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JBackAddDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 150, 80));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PinCode");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 90, 30));
        jPanel2.add(JPinCodePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 150, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 600, 90, 30));
        jPanel2.add(JEmailPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 160, 30));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Weight (in Kgs)");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, 110, 30));
        jPanel2.add(JHeightPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, 150, 30));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Height (in cms)");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 110, 30));
        jPanel2.add(JWeightPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 680, 150, 30));

        JCommunityPat.setToolTipText("");
        jPanel2.add(JCommunityPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 140, 30));
        jPanel2.add(JCountryPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 160, 30));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Community");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 100, 30));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Country");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 940));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFNamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFNamePatKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            JFNamePat.setEditable(true);
        } else {
            JFNamePat.setEditable(false);
        }
    }//GEN-LAST:event_JFNamePatKeyPressed

    private void JLNamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLNamePatKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            JLNamePat.setEditable(true);
        } else {
            JLNamePat.setEditable(false);
        }
    }//GEN-LAST:event_JLNamePatKeyPressed

    private void JAgePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JAgePatKeyPressed
        // TODO add your handling code here:
        String CellNumber = JAgePat.getText();
        int length = CellNumber.length();
        char c = evt.getKeyChar();

        //check for number 0 to 1
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 2 digit
            if(length<2){
                JAgePat.setEditable(true);

            } else{
                JAgePat.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                JAgePat.setEditable(true);
            } else{
                JAgePat.setEditable(false);
            }
        }
    }//GEN-LAST:event_JAgePatKeyPressed

    private void JGenderPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JGenderPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JGenderPatActionPerformed

    private void JPhoneNoPatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPhoneNoPatKeyPressed
        // TODO add your handling code here:
        try{
            String CellNumber = JPhoneNoPat.getText();
            int length = CellNumber.length();
            char c = evt.getKeyChar();

            //check for number 0 to 9
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                //check for length not more than 10 digit
                if(length<10){
                    JPhoneNoPat.setEditable(true);

                } else{
                    JPhoneNoPat.setEditable(false);
                }
            }else{
                if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    JPhoneNoPat.setEditable(true);
                } else{
                    JPhoneNoPat.setEditable(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_JPhoneNoPatKeyPressed

    private void JSaveDocButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSaveDocButtonMouseClicked
        // TODO add your handling code here:

        String patID = JPatID.getText();
        String fname = JFNamePat.getText();
        String lname = JLNamePat.getText();
        int age = Integer.parseInt(JAgePat.getText());
        String gender = JGenderPat.getSelectedItem().toString();
        String community = JCommunityPat.getText();
        String country = JCountryPat.getText();
        String streetaddress = JAddressPat.getText();
        String pincode = JPinCodePat.getText();
        String bloodgroup = JBGroupPat.getText();
        String phoneNo = JPhoneNoPat.getText();
        String city = JCityPat.getText();
        Date JoiningDate = JVisitDatePat.getDate();
        String email = JEmailPat.getText();
        double height = Double.parseDouble(JHeightPat.getText());
        double weight = Double.parseDouble(JWeightPat.getText());
        int length = phoneNo.length();

        //DocData dd = DocDirectory.addNewDocData();
        if (patID.isEmpty() || fname.isEmpty()|| lname.isEmpty() ||/* age.isEmpty()||*/ bloodgroup.isEmpty()
            || gender.isEmpty() || community.isEmpty() || country.isEmpty() ||streetaddress.isEmpty() ||
            /*phoneNo.isEmpty() || */ city.isEmpty() || email.isEmpty()/*|| JoiningDate.isEmpty()*/){
            JOptionPane.showMessageDialog(this,
                "Please enter all fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else if(length<10){
            JOptionPane.showMessageDialog(this,
                "Please enter cell no of 10 digits",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email)))
        {
            JOptionPane.showMessageDialog(null,
                "Please enter a valid email",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else{
            PatData pd = PatDirectory.addNewpatData();
            pd.setFName(fname);
            pd.setLName(lname);
            pd.setPatientID(patID);
            pd.setBloodgroup(bloodgroup);        
            pd.setGender(gender);
            pd.setAge(age);
            pd.setPhoneNo(phoneNo);
            pd.setVisitingDate(JoiningDate);
            pd.setEmailAddress(email);
            
            House PatHouse = new House();
            PatHouse.setStreetAddress(streetaddress);
            pd.setHouse(PatHouse);
        
            City PatCity = new City();
            PatCity.setCity(city);
            pd.setCity(PatCity);
        
            Community PatCommunity = new Community();
            PatCommunity.setCommunityName(community);               
            pd.setCommunity(PatCommunity);
        
            Community Patpincode = new Community();
            Patpincode.setPincode(pincode);
            pd.setPincode(Patpincode);
        
        //docCommunity.setPincode(pincode);   
           City PatCountry = new City();
           PatCountry.setCountry(country);
           pd.setCountry(PatCountry);
            
            

            JOptionPane.showMessageDialog(this, "New record added");

            JPatID.setText("");
            JFNamePat.setText("");
            JLNamePat.setText("");
            JAgePat.setText("");
            JBGroupPat.setText("");
            JGenderPat.setSelectedIndex(0);
            JCountryPat.setText("");
            JCommunityPat.setText("");
            JCityPat.setText("");
            JAddressPat.setText("");
            JPhoneNoPat.setText("");
            JPinCodePat.setText("");
            JEmailPat.setText("");
            JHeightPat.setText("");
            JWeightPat.setText("");

        }
        //String DocID = JDocID.getText();
        //String FName

        /*
        DoctorDirectory DocDirectory = new DoctorDirectory();
        DocDirectory.setDocID(JDocID.getText());
        DocDirec.setFNameDoc(JFNameDoc.getText());
        DocDirec.setLNameDoc(JLNameDoc.getText());
        DocDirec.setAgeDoc(Integer.parseInt(JAgeDoc.getText()));
        DocDirec.setBGroupDoc(JBGroupDoc.getText());
        DocDirec.setGenderDoc(JGenderDoc.getSelectedItem().toString());
        DocDirec.setDepartmentDoc(JDepartmentDoc.getSelectedItem().toString());
        DocDirec.setAddressDoc(JAddressDoc.getText());
        DocDirec.setCityDoc(JCityDoc.getText());
        DocDirec.setPhoneNoDoc(Integer.parseInt(JPhoneNoDoc.getText()));
        DocDirec.setJoiningDateDoc(JJoiningDateDoc.getDate());

        */

        /*
        if (DocDirec.getDocID().isEmpty() || DocDirec.getFNameDoc().isEmpty()|| DocDirec.getLNameDoc().isEmpty() || /*DocDirec.getAgeDoc().isEmpty()|| DocDirec.getBGroupDoc().isEmpty()
            || DocDirec.getGenderDoc().isEmpty() || DocDirec.getDepartmentDoc().isEmpty() || DocDirec.getAddressDoc().isEmpty() ||
            DocDirec.getPhoneNoDoc().isEmpty() ||  DocDirec.getCityDoc().isEmpty() /*|| DocDirec.getJoiningDateDoc().isEmpty)){
        JOptionPane.showMessageDialog(this,
            "Please enter all fields",
            "Try Again",
            JOptionPane.ERROR_MESSAGE);
        } else if(DocDirec.getPhoneNoDoc()<10){
            JOptionPane.showMessageDialog(this,
                "Please enter cell no of 10 digits",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);

        }
        else{
            JOptionPane.showMessageDialog(this, "Doctor Details Added");

            JDocID.setText("");
            JFNameDoc.setText("");
            JLNameDoc.setText("");
            JAgeDoc.setText("");
            JBGroupDoc.setText("");
            JGenderDoc.setSelectedIndex(0);
            JDepartmentDoc.setSelectedIndex(0);
            JCityDoc.setText("");
            JAddressDoc.setText("");
            JPhoneNoDoc.setText("");

        }

        /*else {
            ViewDoctorDetails Vdd = new ViewDoctorDetails();
            DefaultTableModel model = (DefaultTableModel) Vdd.JTableDoc.getModel();
            model.addRow( new Object[] {name, empid, age, gender, date, level, teaminfo,
                positiontitle, cellphoneno, email, ImageLabel});

        TFName.setText("");
        TFEmpID.setText("");
        TFAge.setText("");
        TFGender.setSelectedIndex(0);
        //TFDateChooser.setDate("yyyy-MM-dd");
        //TFDateChooser.setCalendar(null);
        TFLevel.setSelectedIndex(0);
        TFTeamInfo.setText("");
        TFPositionTitle.setText("");
        TFCellPhoneNo.setText("");
        TFEmailAdd.setText("");
        image_txt.setText("");

        }
        */

    }//GEN-LAST:event_JSaveDocButtonMouseClicked

    private void JBackAddDoctorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackAddDoctorButtonMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_JBackAddDoctorButtonMouseClicked

    private void JBackAddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackAddDoctorButtonActionPerformed
        // TODO add your handling code here:

        PatientDetailsAdmin PDA = new PatientDetailsAdmin(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        PDA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBackAddDoctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JAddressPat;
    private javax.swing.JTextField JAgePat;
    private javax.swing.JTextField JBGroupPat;
    private javax.swing.JButton JBackAddDoctorButton;
    private javax.swing.JTextField JCityPat;
    private javax.swing.JTextField JCommunityPat;
    private javax.swing.JTextField JCountryPat;
    private javax.swing.JTextField JEmailPat;
    private javax.swing.JTextField JFNamePat;
    private javax.swing.JComboBox<String> JGenderPat;
    private javax.swing.JTextField JHeightPat;
    private javax.swing.JTextField JLNamePat;
    private javax.swing.JTextField JPatID;
    private javax.swing.JTextField JPhoneNoPat;
    private javax.swing.JTextField JPinCodePat;
    private javax.swing.JButton JSaveDocButton;
    private com.toedter.calendar.JDateChooser JVisitDatePat;
    private javax.swing.JTextField JWeightPat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
