/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.DoctorDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class CommunityAdmins extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdmins
     */
    DoctorDirectory DocDirectory;
    HospitalDirectory HospDirectory;
    PatientDirectory PatDirectory;
    
    public CommunityAdmins() {
        initComponents();
   
    }
    
    CommunityAdmins(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         initComponents();

        this.DocDirectory = DocDirectory;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JAssignHospBtn = new javax.swing.JButton();
        btnBackDoctorDetailsAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JAssignHospBtn.setBackground(new java.awt.Color(0, 102, 153));
        JAssignHospBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JAssignHospBtn.setForeground(new java.awt.Color(255, 255, 255));
        JAssignHospBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/add-user-3.png")); // NOI18N
        JAssignHospBtn.setText("Assign Hospital");
        JAssignHospBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JAssignHospBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JAssignHospBtnMouseClicked(evt);
            }
        });
        jPanel1.add(JAssignHospBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 60));

        btnBackDoctorDetailsAdmin.setBackground(new java.awt.Color(0, 153, 204));
        btnBackDoctorDetailsAdmin.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        btnBackDoctorDetailsAdmin.setText("Back");
        btnBackDoctorDetailsAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackDoctorDetailsAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackDoctorDetailsAdminMouseClicked(evt);
            }
        });
        btnBackDoctorDetailsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDoctorDetailsAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackDoctorDetailsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JAssignHospBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAssignHospBtnMouseClicked
        // TODO add your handling code here:
        CommunityAdminDetails CAD = new CommunityAdminDetails(DocDirectory, HospDirectory, PatDirectory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        CAD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JAssignHospBtnMouseClicked

    private void btnBackDoctorDetailsAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_btnBackDoctorDetailsAdminMouseClicked

    private void btnBackDoctorDetailsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminActionPerformed
        // TODO add your handling code here:

        //DoctorDetailsAdmin DDA = new DoctorDetailsAdmin(DocDirectory);
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackDoctorDetailsAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAssignHospBtn;
    private javax.swing.JButton btnBackDoctorDetailsAdmin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
