/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class CommunityAdmins extends javax.swing.JFrame {

    /**
     * Creates new form CommunityAdmins
     */
    DoctorDirectory DocDirectory;
    HospitalDirectory HospDirectory;
    PatientDirectory PatDirectory;
    CityDirectory cityDirectory;
    CommunityDirectory CommDirectory;
    EncounterHistory EncHistory;
    
    public CommunityAdmins() {
        initComponents();
   
    }
    
    CommunityAdmins(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory,  CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         initComponents();

        this.DocDirectory = DocDirectory;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
        this.EncHistory = EncHistory;
        
        
         
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JCreateCityBtn = new javax.swing.JButton();
        btnBackCommunityAdmins = new javax.swing.JButton();
        JAssignHospBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCreateCityBtn.setBackground(new java.awt.Color(0, 102, 153));
        JCreateCityBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JCreateCityBtn.setForeground(new java.awt.Color(255, 255, 255));
        JCreateCityBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/add-user-3.png")); // NOI18N
        JCreateCityBtn.setText("Add City & Community");
        JCreateCityBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JCreateCityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JCreateCityBtnMouseClicked(evt);
            }
        });
        jPanel1.add(JCreateCityBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 230, 60));

        btnBackCommunityAdmins.setBackground(new java.awt.Color(0, 153, 204));
        btnBackCommunityAdmins.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        btnBackCommunityAdmins.setText("Back");
        btnBackCommunityAdmins.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackCommunityAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackCommunityAdminsMouseClicked(evt);
            }
        });
        btnBackCommunityAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCommunityAdminsActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackCommunityAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 150, 60));

        JAssignHospBtn1.setBackground(new java.awt.Color(0, 102, 153));
        JAssignHospBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JAssignHospBtn1.setForeground(new java.awt.Color(255, 255, 255));
        JAssignHospBtn1.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/add-user-3.png")); // NOI18N
        JAssignHospBtn1.setText("Assign Hospital");
        JAssignHospBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JAssignHospBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JAssignHospBtn1MouseClicked(evt);
            }
        });
        jPanel1.add(JAssignHospBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCreateCityBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCreateCityBtnMouseClicked
        // TODO add your handling code here:
        AddCityCommunity Acc = new AddCityCommunity(DocDirectory, HospDirectory, PatDirectory, cityDirectory,CommDirectory, EncHistory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JCreateCityBtnMouseClicked

    private void btnBackCommunityAdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCommunityAdminsMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_btnBackCommunityAdminsMouseClicked

    private void btnBackCommunityAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCommunityAdminsActionPerformed
        // TODO add your handling code here:

        //DoctorDetailsAdmin DDA = new DoctorDetailsAdmin(DocDirectory);
        LoginPage lp = new LoginPage(DocDirectory, HospDirectory, PatDirectory, cityDirectory,CommDirectory, EncHistory );
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackCommunityAdminsActionPerformed

    private void JAssignHospBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAssignHospBtn1MouseClicked
        // TODO add your handling code here:
        CommunityAdminDetails CAD = new CommunityAdminDetails(DocDirectory, HospDirectory, PatDirectory, cityDirectory,CommDirectory, EncHistory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        CAD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JAssignHospBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommunityAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommunityAdmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAssignHospBtn1;
    private javax.swing.JButton JCreateCityBtn;
    private javax.swing.JButton btnBackCommunityAdmins;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
