/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.DoctorDirectory;
import model.HospitalDirectory;
import model.PatientDirectory;

public class DoctorDetailsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDetailsAdmin
     */
    
    DoctorDirectory DocDirectory;
    PatientDirectory PatDirectory;
    HospitalDirectory HospDirectory;
    
    public DoctorDetailsAdmin() {
        initComponents();
        
        //DocDirectory = new DoctorDirectory();
        
        //addDefaultData(this.DocDirectory);
            
    }

//    DoctorDetailsAdmin(DoctorDirectory DocDirectory) { 
//        initComponents();
//       
//        this.DocDirectory = DocDirectory;  //we are pushing whole reference to DoctorDirectory
// 
//    }

//    DoctorDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
//        initComponents();
//       
//        this.DocDirectory = DocDirectory;  //we are pushing whole reference to DoctorDirectory
//        this.PatDirectory = PatDirectory;
//        this.HospDirectory = HospDirectory;
//    }

    DoctorDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory) {
        //new throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.DocDirectory = DocDirectory;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        
                
    }

//    DoctorDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

//    DoctorDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
//
//      
    

    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JViewDocBtn = new javax.swing.JButton();
        JAddDoctorButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnBackDoctorDetailsAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JViewDocBtn.setBackground(new java.awt.Color(0, 102, 153));
        JViewDocBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JViewDocBtn.setForeground(new java.awt.Color(255, 255, 255));
        JViewDocBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/file.png")); // NOI18N
        JViewDocBtn.setText("View Doctor");
        JViewDocBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JViewDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JViewDocBtnActionPerformed(evt);
            }
        });
        jPanel2.add(JViewDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 160, 60));

        JAddDoctorButton.setBackground(new java.awt.Color(0, 102, 153));
        JAddDoctorButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JAddDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        JAddDoctorButton.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/add-user-3.png")); // NOI18N
        JAddDoctorButton.setText("Add Doctor");
        JAddDoctorButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JAddDoctorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JAddDoctorButtonMouseClicked(evt);
            }
        });
        jPanel2.add(JAddDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 60));

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/refresh.png")); // NOI18N
        jButton3.setText("Update Doctor");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 160, 60));

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/search.png")); // NOI18N
        jButton5.setText("Search Doctor");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 160, 60));

        btnBackDoctorDetailsAdmin.setBackground(new java.awt.Color(0, 153, 204));
        btnBackDoctorDetailsAdmin.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        btnBackDoctorDetailsAdmin.setText("Back");
        btnBackDoctorDetailsAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackDoctorDetailsAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackDoctorDetailsAdminMouseClicked(evt);
            }
        });
        btnBackDoctorDetailsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDoctorDetailsAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnBackDoctorDetailsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 150, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 6, 1470, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JViewDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JViewDocBtnActionPerformed
        // TODO add your handling code here:
        
        ViewDoctorDetails Vdd = new ViewDoctorDetails(DocDirectory, HospDirectory, PatDirectory );     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Vdd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JViewDocBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JAddDoctorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAddDoctorButtonMouseClicked
        // TODO add your handling code here:
        AddDoctorDetails1 Add = new AddDoctorDetails1(DocDirectory, HospDirectory, PatDirectory );     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JAddDoctorButtonMouseClicked

    private void btnBackDoctorDetailsAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_btnBackDoctorDetailsAdminMouseClicked

    private void btnBackDoctorDetailsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminActionPerformed
        // TODO add your handling code here:

        //DoctorDetailsAdmin DDA = new DoctorDetailsAdmin(DocDirectory);
       SystemAdmin SA = new SystemAdmin(DocDirectory, HospDirectory, PatDirectory);
       SA.setVisible(true); 
       this.dispose();
    }//GEN-LAST:event_btnBackDoctorDetailsAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDetailsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAddDoctorButton;
    private javax.swing.JButton JViewDocBtn;
    private javax.swing.JButton btnBackDoctorDetailsAdmin;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
