/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class HospitalDetailsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HospitalDetailsAdmin
     * 
     */
    
      HospitalDirectory HospDirectory;
      DoctorDirectory DocDirectory;
      PatientDirectory PatDirectory;
      CityDirectory cityDirectory;
      CommunityDirectory CommDirectory;
      EncounterHistory EncHistory;
    
      
    public HospitalDetailsAdmin() {
        initComponents();
        
//        HospDirectory = new HospitalDirectory();
    }

//    HospitalDetailsAdmin(HospitalDirectory HospDirectory) {
//         initComponents();
//       
//        this.HospDirectory = HospDirectory;
//    }

    HospitalDetailsAdmin(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory,  CommunityDirectory CommDirectory,EncounterHistory EncHistory) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.DocDirectory = DocDirectory;
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
        this.EncHistory = EncHistory;
    }

    
    

    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JAddDoctorButton = new javax.swing.JButton();
        JViewDocBtn = new javax.swing.JButton();
        btnBackDoctorDetailsAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JAddDoctorButton.setBackground(new java.awt.Color(0, 102, 153));
        JAddDoctorButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JAddDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        JAddDoctorButton.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/add-user-3.png")); // NOI18N
        JAddDoctorButton.setText("Add Hospital");
        JAddDoctorButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JAddDoctorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JAddDoctorButtonMouseClicked(evt);
            }
        });
        jPanel1.add(JAddDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 60));

        JViewDocBtn.setBackground(new java.awt.Color(0, 102, 153));
        JViewDocBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JViewDocBtn.setForeground(new java.awt.Color(255, 255, 255));
        JViewDocBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/file.png")); // NOI18N
        JViewDocBtn.setText("View Hospital");
        JViewDocBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JViewDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JViewDocBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JViewDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 60));

        btnBackDoctorDetailsAdmin.setBackground(new java.awt.Color(0, 153, 204));
        btnBackDoctorDetailsAdmin.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        btnBackDoctorDetailsAdmin.setText("Back");
        btnBackDoctorDetailsAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackDoctorDetailsAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackDoctorDetailsAdminMouseClicked(evt);
            }
        });
        btnBackDoctorDetailsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDoctorDetailsAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackDoctorDetailsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 150, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JAddDoctorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JAddDoctorButtonMouseClicked
        // TODO add your handling code here:
        AddHospitalDetails Ahd = new AddHospitalDetails(DocDirectory, HospDirectory, PatDirectory, cityDirectory,CommDirectory, EncHistory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Ahd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JAddDoctorButtonMouseClicked

    private void JViewDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JViewDocBtnActionPerformed
        // TODO add your handling code here:

        ViewHospitalDetails Vhd = new ViewHospitalDetails(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);     //Add doctor needs reference through DoctorDirectory to DocDirectory variable. DoctorDirectory needs to know the referennce in order to save the data for doctor.
        Vhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JViewDocBtnActionPerformed

    private void btnBackDoctorDetailsAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_btnBackDoctorDetailsAdminMouseClicked

    private void btnBackDoctorDetailsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDoctorDetailsAdminActionPerformed
        // TODO add your handling code here:

        //DoctorDetailsAdmin DDA = new DoctorDetailsAdmin(DocDirectory);
        SystemAdmin SA = new SystemAdmin(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        SA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackDoctorDetailsAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalDetailsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalDetailsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAddDoctorButton;
    private javax.swing.JButton JViewDocBtn;
    private javax.swing.JButton btnBackDoctorDetailsAdmin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
