/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.DoctorModel;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.PatientDirectory;




/**
 *
 * @author anupamaditya
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    

  DoctorModel doctorModel;
  DoctorDirectory DocDirectory;
  PatientDirectory PatDirectory;
  HospitalDirectory HospDirectory;
  CityDirectory cityDirectory;
  CommunityDirectory CommDirectory;
  EncounterHistory EncHistory;
    
    public LoginPage() {
        initComponents();
        DocDirectory = new DoctorDirectory();
        PatDirectory  = new PatientDirectory();
        HospDirectory = new HospitalDirectory();
        cityDirectory = new CityDirectory();
        CommDirectory = new CommunityDirectory();
        EncHistory = new EncounterHistory();
    }
    
    public LoginPage(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory, CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        initComponents();
   
      //  this.doctorModel = doctorModel;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.DocDirectory = DocDirectory;
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
        this.EncHistory= EncHistory;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JCommunityAdminButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JDoctorButton = new javax.swing.JButton();
        JPatientButton = new javax.swing.JButton();
        JSystemAdminButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JHospitalAdminBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/engineer.png")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(450, 430, 130, 140);

        JCommunityAdminButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JCommunityAdminButton.setForeground(new java.awt.Color(0, 102, 153));
        JCommunityAdminButton.setText("Community Admins");
        JCommunityAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCommunityAdminButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JCommunityAdminButton);
        JCommunityAdminButton.setBounds(420, 580, 190, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/medical-team.png")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(680, 430, 130, 140);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/patient-2.png")); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(900, 420, 140, 140);

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/project-manager.png")); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 430, 130, 140);

        JDoctorButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JDoctorButton.setForeground(new java.awt.Color(0, 102, 153));
        JDoctorButton.setText("Doctors");
        JDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JDoctorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JDoctorButton);
        JDoctorButton.setBounds(670, 580, 170, 40);

        JPatientButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JPatientButton.setForeground(new java.awt.Color(0, 102, 153));
        JPatientButton.setText("Patient");
        JPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPatientButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JPatientButton);
        JPatientButton.setBounds(900, 580, 170, 40);

        JSystemAdminButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JSystemAdminButton.setForeground(new java.awt.Color(0, 102, 153));
        JSystemAdminButton.setText("System Admin");
        JSystemAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSystemAdminButtonActionPerformed(evt);
            }
        });
        jPanel2.add(JSystemAdminButton);
        JSystemAdminButton.setBounds(200, 580, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/image-3.png")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(630, 310, 250, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/user-4.png")); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(1130, 430, 140, 140);

        JHospitalAdminBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        JHospitalAdminBtn.setForeground(new java.awt.Color(0, 102, 153));
        JHospitalAdminBtn.setText("Hospital Admin");
        JHospitalAdminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JHospitalAdminBtnMouseClicked(evt);
            }
        });
        JHospitalAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHospitalAdminBtnActionPerformed(evt);
            }
        });
        jPanel2.add(JHospitalAdminBtn);
        JHospitalAdminBtn.setBounds(1120, 580, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/resize-1666366531100659092ADMINLOGIN1.png")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -100, 1430, 1020);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JSystemAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSystemAdminButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminLogin SAL = new SystemAdminLogin(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        SAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JSystemAdminButtonActionPerformed

    private void JCommunityAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCommunityAdminButtonActionPerformed
        // TODO add your handling code here:
        CommunityAdmins CA = new CommunityAdmins(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        CA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JCommunityAdminButtonActionPerformed

    private void JDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDoctorButtonActionPerformed
        // TODO add your handling code here:
        DoctorLogin Doc = new DoctorLogin(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        Doc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JDoctorButtonActionPerformed

    private void JPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPatientButtonActionPerformed
        // TODO add your handling code here:
        PatientLogin PatLogin = new PatientLogin();
        PatLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JPatientButtonActionPerformed

    private void JHospitalAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHospitalAdminBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JHospitalAdminBtnActionPerformed

    private void JHospitalAdminBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JHospitalAdminBtnMouseClicked
        // TODO add your handling code here:
        HospitalAdminLogin HAL = new HospitalAdminLogin();
        HAL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JHospitalAdminBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCommunityAdminButton;
    private javax.swing.JButton JDoctorButton;
    private javax.swing.JButton JHospitalAdminBtn;
    private javax.swing.JButton JPatientButton;
    private javax.swing.JButton JSystemAdminButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
