/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anupamaditya
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JBackSearchHospInPatBtn = new javax.swing.JButton();
        SearchPat = new javax.swing.JLabel();
        TFSearchPat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Search Hospitals");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 80));

        JBackSearchHospInPatBtn.setBackground(new java.awt.Color(0, 153, 204));
        JBackSearchHospInPatBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/logout-2.png")); // NOI18N
        JBackSearchHospInPatBtn.setText("Logout");
        JBackSearchHospInPatBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackSearchHospInPatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackSearchHospInPatBtnMouseClicked(evt);
            }
        });
        JBackSearchHospInPatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackSearchHospInPatBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JBackSearchHospInPatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 150, 80));

        SearchPat.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SearchPat.setForeground(new java.awt.Color(255, 255, 255));
        SearchPat.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/search.png")); // NOI18N
        SearchPat.setText("Enter Hospital Name or Community Name");
        SearchPat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(SearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 340, 40));

        TFSearchPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSearchPatActionPerformed(evt);
            }
        });
        TFSearchPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFSearchPatKeyReleased(evt);
            }
        });
        jPanel1.add(TFSearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 550, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Phone No", "Email", "Community", "City", "Pincode"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 950, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackSearchHospInPatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackSearchHospInPatBtnMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_JBackSearchHospInPatBtnMouseClicked

    private void JBackSearchHospInPatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackSearchHospInPatBtnActionPerformed
        // TODO add your handling code here:

        JFrame frame = new JFrame("Logout");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to logout", "logout", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            //System.exit(0);
             PatientLogin PL = new PatientLogin();
             PL.setVisible(true);
        }
    }//GEN-LAST:event_JBackSearchHospInPatBtnActionPerformed

    private void TFSearchPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSearchPatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TFSearchPatActionPerformed

    private void TFSearchPatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSearchPatKeyReleased
        // TODO add your handling code here:

//        String search = TFSearchPat.getText();
//        search(search);
    }//GEN-LAST:event_TFSearchPatKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBackSearchHospInPatBtn;
    private javax.swing.JLabel SearchPat;
    private javax.swing.JTextField TFSearchPat;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
