/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import model.DoctorModel;

/**
 *
 * @author anupamaditya
 */
public class PatientLogin extends javax.swing.JFrame {

    /**
     * Creates new form DoctorLogin
     */
    public PatientLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LoginDoc = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText(" PATIENT'S LOGIN PANEL");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1100, 280, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/user-2.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1080, 340, 30, 50);

        JUserName.setOpaque(true);
        JUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(JUserName);
        JUserName.setBounds(1140, 350, 200, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/lock.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1080, 410, 50, 60);

        LoginDoc.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        LoginDoc.setForeground(new java.awt.Color(0, 102, 153));
        LoginDoc.setText("Login");
        LoginDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginDocActionPerformed(evt);
            }
        });
        jPanel1.add(LoginDoc);
        LoginDoc.setBounds(1080, 510, 110, 30);

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("Clear");
        jPanel1.add(jButton2);
        jButton2.setBounds(1230, 510, 110, 30);
        jPanel1.add(JPassword);
        JPassword.setBounds(1140, 430, 200, 30);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1170, 550, 72, 23);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 4));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1040, 270, 340, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/drback-3.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 1510, 890);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1507, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUserNameActionPerformed

    private void LoginDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginDocActionPerformed
        // TODO add your handling code here:
        DoctorModel doc = new DoctorModel();
        doc.setUserName(JUserName.getText());
        doc.setPassWord(JPassword.getText());
        
         if (doc.getUserName().isEmpty() || doc.getPassWord().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Please enter all fields",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
        return;
        //username = Doctoradmin & password = abcde
         }
        if (doc.getUserName().equals("Patadmin") && doc.getPassWord().equals("abcde")){
            Patient Pat1 = new Patient();
            Pat1.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,
                    "Please enter correct username or password",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);     
       }  
    }//GEN-LAST:event_LoginDocActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        lp.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPassword;
    private javax.swing.JTextField JUserName;
    private javax.swing.JButton LoginDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
