/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import model.CityDirectory;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
import model.PatientDirectory;

/**
 *
 * @author anupamaditya
 */
public class ViewPatientVital extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatientVital
     */
    
    
    DoctorDirectory DocDirectory;
    PatientDirectory PatDirectory;
    HospitalDirectory HospDirectory;
    CityDirectory cityDirectory;
    CommunityDirectory CommDirectory;
     EncounterHistory EncHistory;
    public ViewPatientVital() {
        initComponents();
    }
    
    public ViewPatientVital(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory, CityDirectory cityDirectory,  CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        initComponents();
        
        this.DocDirectory = DocDirectory;
        this.PatDirectory = PatDirectory;
        this.HospDirectory = HospDirectory;
        this.cityDirectory = cityDirectory;
        this.CommDirectory = CommDirectory;
         this.EncHistory= EncHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JBackViewPatientVitalBtn = new javax.swing.JButton();
        SearchPat = new javax.swing.JLabel();
        TFSearchPat = new javax.swing.JTextField();
        jBtnDeletePatVitals = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableVitals = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JPatID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPatName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JVisitDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        JTFTempearture = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFBPressure = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFPulseRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTFRespirationRate = new javax.swing.JTextField();
        JUpdatePatientVitalBtn = new javax.swing.JButton();
        JViewPatientVitalBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Patient Vital Signs");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 80));

        JBackViewPatientVitalBtn.setBackground(new java.awt.Color(0, 153, 204));
        JBackViewPatientVitalBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        JBackViewPatientVitalBtn.setText("Back");
        JBackViewPatientVitalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackViewPatientVitalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackViewPatientVitalBtnMouseClicked(evt);
            }
        });
        JBackViewPatientVitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackViewPatientVitalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JBackViewPatientVitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 150, 80));

        SearchPat.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SearchPat.setForeground(new java.awt.Color(255, 255, 255));
        SearchPat.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/search.png")); // NOI18N
        SearchPat.setText("Enter Patient Name");
        SearchPat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(SearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 200, 40));

        TFSearchPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSearchPatActionPerformed(evt);
            }
        });
        TFSearchPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFSearchPatKeyReleased(evt);
            }
        });
        jPanel1.add(TFSearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 570, 40));

        jBtnDeletePatVitals.setBackground(new java.awt.Color(0, 105, 153));
        jBtnDeletePatVitals.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnDeletePatVitals.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDeletePatVitals.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/trash.png")); // NOI18N
        jBtnDeletePatVitals.setText("Delete");
        jBtnDeletePatVitals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnDeletePatVitals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDeletePatVitalsMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnDeletePatVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, 150, 40));

        JTableVitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Visit Date", "Temperature", "Blood Pressure", "Pulse Rate", "Respiration Rate"
            }
        ));
        jScrollPane1.setViewportView(JTableVitals);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 1010, 410));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 30));
        jPanel1.add(JPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 30));

        JPatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPatNameActionPerformed(evt);
            }
        });
        jPanel1.add(JPatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Visit Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 30));
        jPanel1.add(JVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Temperature");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, 30));

        JTFTempearture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTempeartureActionPerformed(evt);
            }
        });
        jPanel1.add(JTFTempearture, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 170, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BPressure");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 100, 30));

        JTFBPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBPressureActionPerformed(evt);
            }
        });
        jPanel1.add(JTFBPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 170, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pulse Rate");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 100, 30));

        JTFPulseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPulseRateActionPerformed(evt);
            }
        });
        jPanel1.add(JTFPulseRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 170, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Respiration Rate");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 120, 30));

        JTFRespirationRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFRespirationRateActionPerformed(evt);
            }
        });
        jPanel1.add(JTFRespirationRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 170, 30));

        JUpdatePatientVitalBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JUpdatePatientVitalBtn.setForeground(new java.awt.Color(0, 102, 153));
        JUpdatePatientVitalBtn.setText("Update");
        JUpdatePatientVitalBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(JUpdatePatientVitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 140, 40));

        JViewPatientVitalBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JViewPatientVitalBtn1.setForeground(new java.awt.Color(0, 102, 153));
        JViewPatientVitalBtn1.setText("View");
        JViewPatientVitalBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(JViewPatientVitalBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBackViewPatientVitalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackViewPatientVitalBtnMouseClicked
        // TODO add your handling code here:
        // DoctorDetailsAdmin DDA = new DoctorDetailsAdmin();
        //DDA.setVisible(true);
    }//GEN-LAST:event_JBackViewPatientVitalBtnMouseClicked

    private void JBackViewPatientVitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackViewPatientVitalBtnActionPerformed
        // TODO add your handling code here:

        DoctorPatPortal DPP1= new DoctorPatPortal(DocDirectory, HospDirectory, PatDirectory, cityDirectory, CommDirectory, EncHistory);
        DPP1.setVisible(true);
    }//GEN-LAST:event_JBackViewPatientVitalBtnActionPerformed

    private void TFSearchPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSearchPatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TFSearchPatActionPerformed

    private void TFSearchPatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSearchPatKeyReleased
        // TODO add your handling code here:

//        String search = TFSearchPat.getText();
//        search(search);
    }//GEN-LAST:event_TFSearchPatKeyReleased

    private void jBtnDeletePatVitalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDeletePatVitalsMouseClicked
        // TODO add your handling code here:
//        int selectedRowIndex = JTablePat.getSelectedRow();
//
//        if(selectedRowIndex<0){
//            JOptionPane.showMessageDialog(this, "Please select row to delete");
//        }
//
//        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
//        PatData selectedPat = (PatData) model.getValueAt(selectedRowIndex, 0);
//
//        PatDirectory.deletePat(selectedPat);
//
//        JOptionPane.showMessageDialog(this, "Doctor Details has been deleted");
//
//        populateTable();
    }//GEN-LAST:event_jBtnDeletePatVitalsMouseClicked

    private void JPatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPatNameActionPerformed

    private void JTFTempeartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTempeartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTempeartureActionPerformed

    private void JTFBPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFBPressureActionPerformed

    private void JTFPulseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPulseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPulseRateActionPerformed

    private void JTFRespirationRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFRespirationRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFRespirationRateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatientVital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatientVital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatientVital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatientVital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatientVital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBackViewPatientVitalBtn;
    private javax.swing.JTextField JPatID;
    private javax.swing.JTextField JPatName;
    private javax.swing.JTextField JTFBPressure;
    private javax.swing.JTextField JTFPulseRate;
    private javax.swing.JTextField JTFRespirationRate;
    private javax.swing.JTextField JTFTempearture;
    private javax.swing.JTable JTableVitals;
    private javax.swing.JButton JUpdatePatientVitalBtn;
    private javax.swing.JButton JViewPatientVitalBtn1;
    private com.toedter.calendar.JDateChooser JVisitDate;
    private javax.swing.JLabel SearchPat;
    private javax.swing.JTextField TFSearchPat;
    private javax.swing.JButton jBtnDeletePatVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
