/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.PatData;
import model.PatientDirectory;
import model.House;
import model.City;
import model.CityDirectory;
import model.Community;
import model.CommunityDirectory;
import model.DoctorDirectory;
import model.EncounterHistory;
import model.HospitalDirectory;
/**
 *
 * @author anupamaditya
 */
public class ViewPatientDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatientDetails
     */
    
       PatientDirectory PatDirectory;
       DoctorDirectory DocDirectory;
       HospitalDirectory HospDirectory;
       CityDirectory cityDirectory;
        CommunityDirectory CommDirectory;
       EncounterHistory EncHistory;
    
       private ViewPatientDetails() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       initComponents();
    }
       
    public ViewPatientDetails(DoctorDirectory DocDirectory, HospitalDirectory HospDirectory, PatientDirectory PatDirectory,CityDirectory cityDirectory,  CommunityDirectory CommDirectory, EncounterHistory EncHistory) {
        initComponents();
        
          this.DocDirectory = DocDirectory;   //we are pushing whole reference to DoctorDirectory
         this.HospDirectory = HospDirectory;
         this.PatDirectory = PatDirectory; 
         this.cityDirectory = cityDirectory;
         this.CommDirectory = CommDirectory;
        
       populateTable();
        
    }

    

    

//    ViewPatientDetails(PatientDirectory PatDirectory, HospitalDirectory HospDirectory, DoctorDirectory DocDirectory) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPatID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JFNamePat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JLNamePat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JAgePat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JBGroupPat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JGenderPat = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JAddressPat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JPinCodePat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JCityPat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JPhoneNoPat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JVisitingDatePat = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        JEmailPat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        JCommunityPat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JCountryPat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablePat = new javax.swing.JTable();
        jBtnViewPatDetails = new javax.swing.JButton();
        JUpdatePatBtn = new javax.swing.JButton();
        SearchPat = new javax.swing.JLabel();
        TFSearchPat = new javax.swing.JTextField();
        jBtnDeleteViewPatientDetails = new javax.swing.JButton();
        JBackPatientViewBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        JHeightPat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        JWeightPat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(JPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, 30));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        JFNamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JFNamePatKeyPressed(evt);
            }
        });
        jPanel1.add(JFNamePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        JLNamePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JLNamePatKeyPressed(evt);
            }
        });
        jPanel1.add(JLNamePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        JAgePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAgePatActionPerformed(evt);
            }
        });
        JAgePat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JAgePatKeyPressed(evt);
            }
        });
        jPanel1.add(JAgePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 150, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Blood Group");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(JBGroupPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 40));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        JGenderPat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " ", " " }));
        JGenderPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JGenderPatActionPerformed(evt);
            }
        });
        jPanel1.add(JGenderPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        jPanel1.add(JAddressPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, 30));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PinCode");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));
        jPanel1.add(JPinCodePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 150, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("City");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));
        jPanel1.add(JCityPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 150, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Phone No");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        JPhoneNoPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPhoneNoPatKeyPressed(evt);
            }
        });
        jPanel1.add(JPhoneNoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 150, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Visiting Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, -1, -1));
        jPanel1.add(JVisitingDatePat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, 150, 30));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, -1, -1));
        jPanel1.add(JEmailPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 770, 150, 30));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Community");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, -1, -1));
        jPanel1.add(JCommunityPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 840, 150, 30));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Country");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        JCountryPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCountryPatActionPerformed(evt);
            }
        });
        jPanel1.add(JCountryPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 150, 30));

        JTablePat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PatID", "FName", "LName", "Age", "Gender", "Blood Group", "Address", "Community", "PinCode", "City", "PhoneNo", "Country", "Visiting Date", "Email", "Height", "Weight"
            }
        ));
        jScrollPane2.setViewportView(JTablePat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 1030, 410));

        jBtnViewPatDetails.setBackground(new java.awt.Color(0, 105, 153));
        jBtnViewPatDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnViewPatDetails.setForeground(new java.awt.Color(255, 255, 255));
        jBtnViewPatDetails.setText("View");
        jBtnViewPatDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnViewPatDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnViewPatDetailsMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnViewPatDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 110, 40));

        JUpdatePatBtn.setBackground(new java.awt.Color(0, 105, 153));
        JUpdatePatBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JUpdatePatBtn.setForeground(new java.awt.Color(255, 255, 255));
        JUpdatePatBtn.setText("Update");
        JUpdatePatBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JUpdatePatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JUpdatePatBtnMouseClicked(evt);
            }
        });
        jPanel1.add(JUpdatePatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 120, 40));

        SearchPat.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        SearchPat.setForeground(new java.awt.Color(255, 255, 255));
        SearchPat.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/search.png")); // NOI18N
        SearchPat.setText("Search");
        SearchPat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(SearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 140, 40));

        TFSearchPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSearchPatActionPerformed(evt);
            }
        });
        TFSearchPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFSearchPatKeyReleased(evt);
            }
        });
        jPanel1.add(TFSearchPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 420, 40));

        jBtnDeleteViewPatientDetails.setBackground(new java.awt.Color(0, 105, 153));
        jBtnDeleteViewPatientDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnDeleteViewPatientDetails.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDeleteViewPatientDetails.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/trash.png")); // NOI18N
        jBtnDeleteViewPatientDetails.setText("Delete");
        jBtnDeleteViewPatientDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnDeleteViewPatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDeleteViewPatientDetailsMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnDeleteViewPatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 150, 40));

        JBackPatientViewBtn.setBackground(new java.awt.Color(0, 153, 204));
        JBackPatientViewBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        JBackPatientViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        JBackPatientViewBtn.setIcon(new javax.swing.ImageIcon("/Users/anupamaditya/Downloads/undo-2.png")); // NOI18N
        JBackPatientViewBtn.setText("Back");
        JBackPatientViewBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBackPatientViewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBackPatientViewBtnMouseClicked(evt);
            }
        });
        JBackPatientViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackPatientViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(JBackPatientViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 140, 40));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Height (in cms)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 110, 30));
        jPanel1.add(JHeightPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 150, 30));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Weight (in Kgs)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 110, 30));
        jPanel1.add(JWeightPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFNamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFNamePatKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            JFNamePat.setEditable(true);
        } else {
            JFNamePat.setEditable(false);
        }
    }//GEN-LAST:event_JFNamePatKeyPressed

    private void JLNamePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLNamePatKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c )|| Character.isISOControl(c)){
            JLNamePat.setEditable(true);
        } else {
            JLNamePat.setEditable(false);
        }
    }//GEN-LAST:event_JLNamePatKeyPressed

    private void JAgePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAgePatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JAgePatActionPerformed

    private void JAgePatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JAgePatKeyPressed
        // TODO add your handling code here:
        String CellNumber = JAgePat.getText();
        int length = CellNumber.length();
        char c = evt.getKeyChar();

        //check for number 0 to 1
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 2 digit
            if(length<2){
                JAgePat.setEditable(true);

            } else{
                JAgePat.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                JAgePat.setEditable(true);
            } else{
                JAgePat.setEditable(false);
            }
        }
    }//GEN-LAST:event_JAgePatKeyPressed

    private void JGenderPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JGenderPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JGenderPatActionPerformed

    private void JPhoneNoPatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPhoneNoPatKeyPressed
        // TODO add your handling code here:
        try{
            String CellNumber = JPhoneNoPat.getText();
            int length = CellNumber.length();
            char c = evt.getKeyChar();

            //check for number 0 to 9
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
                //check for length not more than 10 digit
                if(length<10){
                    JPhoneNoPat.setEditable(true);

                } else{
                    JPhoneNoPat.setEditable(false);
                }
            }else{
                if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                    JPhoneNoPat.setEditable(true);
                } else{
                    JPhoneNoPat.setEditable(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_JPhoneNoPatKeyPressed

    private void JCountryPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCountryPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCountryPatActionPerformed

    private void jBtnViewPatDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnViewPatDetailsMouseClicked
        // TODO add your handling code here:

        int selectedRowIndex = JTablePat.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
        PatData selectedPat = (PatData) model.getValueAt(selectedRowIndex, 0);

        JPatID.setText(String.valueOf(selectedPat.getPatientID()));  //here String.valueof is used to convert any data type like int to String.
        //JDocID.setEditable(false);

        JFNamePat.setText(String.valueOf(selectedPat.getFName()));
        //JFNameDoc.setEditable(false);

        JLNamePat.setText(String.valueOf(selectedPat.getLName()));
        //JLNameDoc.setEditable(false);

        JAgePat.setText(String.valueOf(selectedPat.getAge()));
        //JAgeDoc.setEditable(false);

        JBGroupPat.setText(String.valueOf(selectedPat.getBloodgroup()));
        //JBGroupDoc.setEditable(false);

        JGenderPat.setSelectedItem(String.valueOf(selectedPat.getGender()));
        //JGenderDoc.setEditable(false);

        House docHouse = selectedPat.getHouse();
        String stAddress = docHouse.getStreetAddress();
        JAddressPat.setText(String.valueOf(stAddress));

        JPhoneNoPat.setText(String.valueOf(selectedPat.getPhoneNo()));
        //JPhoneNoDoc.setEditable(false);

        City docCity = selectedPat.getCity();
        String city = docCity.getCity();
        JCityPat.setText(String.valueOf(city));

        //JCityDoc.setText(String.valueOf(selectedDoc.getCity()));
        //JCityDoc.setEditable(false);

        JVisitingDatePat.setDate(selectedPat.getVisitingDate());
        // JJoiningDateDoc.setEnabled(false);

        Community docCommunity = selectedPat.getCommunity();
        String docComm = docCommunity.getCommunityName();
        JCommunityPat.setText(String.valueOf(docComm));

        Community docpincode = selectedPat.getPincode();
        String docpcode = docpincode.getPincode();
        JPinCodePat.setText(String.valueOf(docpcode));

        City docCountry = selectedPat.getCountry();
        String country = docCountry.getCountry();
        JCountryPat.setText(String.valueOf(country));

        JEmailPat.setText(String.valueOf(selectedPat.getEmailAddress()));
        JHeightPat.setText(String.valueOf(selectedPat.getHeightInCms()));
        JWeightPat.setText(String.valueOf(selectedPat.getWeightInKgs()));

    }//GEN-LAST:event_jBtnViewPatDetailsMouseClicked

    private void JUpdatePatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JUpdatePatBtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
        if (JTablePat.getSelectedRowCount()==1){

            String patientID = JPatID.getText();
            String fname = JFNamePat.getText();
            String lname = JLNamePat.getText();
            int age = Integer.parseInt(JAgePat.getText());
            String gender = JGenderPat.getSelectedItem().toString();
            String address = JAddressPat.getText();
            String country = JCountryPat.getText();
            String community = JCommunityPat.getText();
            String bloodgroup = JBGroupPat.getText();
            String phoneNo = JPhoneNoPat.getText();
            String city = JCityPat.getText();
            Date VisitingDate = JVisitingDatePat.getDate();
            String pincode = JPinCodePat.getText();
            String email = JEmailPat.getText();
            double height = Double.parseDouble(JHeightPat.getText());
            double weight = Double.parseDouble(JWeightPat.getText());
            int x= 0;
            //String image = image_txt.getText();
            //int length = cellphoneno.length();

            int length = phoneNo.length();
            if(length<10){
                JOptionPane.showMessageDialog(this,
                    "Please enter cell no of 10 digits",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
                x=1;

            } else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email)))
            {
                JOptionPane.showMessageDialog(null,
                    "Please enter a valid email",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                x=1;

            } if(x!=1){
                model.setValueAt(patientID, JTablePat.getSelectedRow(),0);
                model.setValueAt(fname, JTablePat.getSelectedRow(),1);
                model.setValueAt(lname, JTablePat.getSelectedRow(),2);
                model.setValueAt(age, JTablePat.getSelectedRow(),3);
                model.setValueAt(gender, JTablePat.getSelectedRow(),4);
                model.setValueAt(bloodgroup, JTablePat.getSelectedRow(),5);
                model.setValueAt(address, JTablePat.getSelectedRow(),6);
                model.setValueAt(community, JTablePat.getSelectedRow(),7);
                model.setValueAt(pincode, JTablePat.getSelectedRow(),8);
                model.setValueAt(city, JTablePat.getSelectedRow(),9);
                model.setValueAt(phoneNo, JTablePat.getSelectedRow(),10);
                model.setValueAt(country, JTablePat.getSelectedRow(),11);
                model.setValueAt(VisitingDate, JTablePat.getSelectedRow(),12);
                model.setValueAt(email, JTablePat.getSelectedRow(),13);
                model.setValueAt(height, JTablePat.getSelectedRow(),14);
                model.setValueAt(weight, JTablePat.getSelectedRow(),15);

                JOptionPane.showMessageDialog(this, "Update Successfully");
            }
        }
        else if (JTablePat.getRowCount()==0){
            //if table is empty
            JOptionPane.showMessageDialog(this, "table is empty");
        } else  {
            //if row is not selected or multiple row is selected
            JOptionPane.showMessageDialog(this, "Please select single row for update");

        }

        JPatID.setText("");
        JFNamePat.setText("");
        JLNamePat.setText("");
        JAgePat.setText("");
        JBGroupPat.setText("");
        JGenderPat.setSelectedIndex(0);
        JCityPat.setText("");
        JAddressPat.setText("");
        JPhoneNoPat.setText("");
        JPinCodePat.setText("");
        JEmailPat.setText("");
        JCommunityPat.setText("");
        JCountryPat.setText("");
        // JJoiningDateDoc.setDate("");
        JHeightPat.setText("");
        JWeightPat.setText("");

    }//GEN-LAST:event_JUpdatePatBtnMouseClicked

    public void search(String str){
        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
        TableRowSorter<DefaultTableModel> trs  = new TableRowSorter<DefaultTableModel>(model);
        JTablePat.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
    }
     
    private void TFSearchPatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSearchPatKeyReleased
        // TODO add your handling code here:

        String search = TFSearchPat.getText();
        search(search);
    }//GEN-LAST:event_TFSearchPatKeyReleased

    private void TFSearchPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSearchPatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TFSearchPatActionPerformed

    private void jBtnDeleteViewPatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDeleteViewPatientDetailsMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = JTablePat.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select row to delete");
        }

        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
        PatData selectedPat = (PatData) model.getValueAt(selectedRowIndex, 0);

        PatDirectory.deletePat(selectedPat);

        JOptionPane.showMessageDialog(this, "Doctor Details has been deleted");

        populateTable();
    }//GEN-LAST:event_jBtnDeleteViewPatientDetailsMouseClicked

    private void JBackPatientViewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBackPatientViewBtnMouseClicked
        // TODO add your handling code here:
        PatientDetailsAdmin pda1 = new PatientDetailsAdmin(DocDirectory, HospDirectory,PatDirectory, cityDirectory, CommDirectory,  EncHistory);
        pda1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBackPatientViewBtnMouseClicked

    private void JBackPatientViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackPatientViewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBackPatientViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JAddressPat;
    private javax.swing.JTextField JAgePat;
    private javax.swing.JTextField JBGroupPat;
    private javax.swing.JButton JBackPatientViewBtn;
    private javax.swing.JTextField JCityPat;
    private javax.swing.JTextField JCommunityPat;
    private javax.swing.JTextField JCountryPat;
    private javax.swing.JTextField JEmailPat;
    private javax.swing.JTextField JFNamePat;
    private javax.swing.JComboBox<String> JGenderPat;
    private javax.swing.JTextField JHeightPat;
    private javax.swing.JTextField JLNamePat;
    private javax.swing.JTextField JPatID;
    private javax.swing.JTextField JPhoneNoPat;
    private javax.swing.JTextField JPinCodePat;
    public javax.swing.JTable JTablePat;
    private javax.swing.JButton JUpdatePatBtn;
    private com.toedter.calendar.JDateChooser JVisitingDatePat;
    private javax.swing.JTextField JWeightPat;
    private javax.swing.JLabel SearchPat;
    private javax.swing.JTextField TFSearchPat;
    private javax.swing.JButton jBtnDeleteViewPatientDetails;
    private javax.swing.JButton jBtnViewPatDetails;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        
        DefaultTableModel model = (DefaultTableModel) JTablePat.getModel();
        model.setRowCount(0);
        
        for(PatData pd : PatDirectory.getPatDirectory()){
            
            Object[] row = new Object[16];
            row[0] =  pd;
            row[1] =  pd.getFName();
            row[2] =  pd.getLName();
            row[3] =  pd.getAge();
            row[4] =  pd.getGender();
            row[5] =  pd.getBloodgroup();
            
            House hd = pd.getHouse();
            row[6] =  hd.getStreetAddress();
            
            Community cc = pd.getCommunity();
            row[7] = cc.getCommunityName();
            
            Community cd = pd.getPincode();
            row[8] =  cd.getPincode();
            
            City cy = pd.getCity();
            row[9] = cy.getCity();
            
            row[10] = pd.getPhoneNo();
            
            City ctry = pd.getCountry();         
            row[11] =  ctry.getCountry();
            
            row[12] = pd.getVisitingDate();
            row[13] = pd.getEmailAddress();
            row[14] = pd.getHeightInCms();
            row[15] = pd.getWeightInKgs();
            
            model.addRow(row);
            
            
        }
        

    }
  }

